# Generated by Django 5.2.9 on 2026-01-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
