# Generated by Django 5.2.9 on 2026-01-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about the author', max_length=500),
        ),
    ]
