# Generated by Django 5.2.9 on 2026-01-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_authorprofile_sociallink_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='joined',
            field=models.DateField(auto_now=True),
        ),
    ]
